services:
#  backend:
#    container_name: backend
#    build: ./backend
#    environment:
#      FLASK_ENV: development
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./backend:/app

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app               # Mount frontend code to /app in container
      - /app/node_modules             # Avoid node_modules conflict on the host
